### ISSUE TITLE
Documention: compare with similar tools

### ISSUE THREAD

**Issue by p3r7** [Lisprez/so_stupid_search#3]
Hi there!

This seems like a nice project.

I would suggest a small comparison with similar tools such as [ripgrep](https://github.com/BurntSushi/ripgrep).

How does it compare in term of goal, scope, behavior?

**Comment by Lisprez** [comment]
> Hi there!
> 
> This seems like a nice project.
> 
> I would suggest a small comparison with similar tools such as [ripgrep](https://github.com/BurntSushi/ripgrep).
> 
> How does it compare in term of goal, scope, behavior?

ripgrep is more powerful than sss.
sss is for simple, small, lazy, the without think when you need to search your text.
while ripgrep is more powerful and large than What I need.
